name: CI

on:
  push:
    branches: [ master, findlibusb ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      target:
        description: 'Upload to "testing" or "production"'     
        required: true
        default: 'testing'

jobs:
  Linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Pull builder image
      run: docker pull quay.io/pypa/manylinux2014_x86_64

    - name: Build wheels
      run: tools/build/build-wheels.sh

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: linux-build
        path: "dist/*.whl"
  
  MacOS:
    runs-on: macos-10.15

    strategy:
      matrix:
        python: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew install python@${{ matrix.python }} sdl2 libusb
          brew link --overwrite python@${{ matrix.python }}
          pip3 install cmake ninja wheel
      
      - name: Build
        run: python3 setup.py bdist_wheel
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: macos-build
          path: "dist/*.whl"

  Windows:
    runs-on: windows-2019

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install wheel

      - name: Build
        run: python setup.py bdist_wheel
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: win-build
          path: "dist/*.whl"
  
  Publish:
    runs-on: ubuntu-latest
    needs: [Linux, MacOS, Windows]
    if: github.event_name == "workflow_dispatch"

    steps:
      - uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R
