name: CI

on:
  push:
    branches: [ master, findlibusb ]
  pull_request:
    branches: [ master ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Pull builder image
      run: docker pull quay.io/pypa/manylinux2014_x86_64

    - name: Build wheels
      run: tools/build/build-wheels.sh
  
  MacOS:
    runs-on: macos-10.15

    steps:
      # Checkout, fetch-depth=0 fetches the full repos (required for automatic versioning to work)
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew install python@3.9 sdl2 libusb
          brew link --overwrite python@3.9
          pip3 install cmake ninja wheel
      
      - name: Build
        run: python3 setup.py bdist_wheel
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: macos-build
          path: "dist/*.whl"
